name: sprawozdanie_pdf
on: push
jobs:
  sprawozdanie_pdf:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install texlive-xetex inkspace pandoc
      - uses: actions/checkout@v4
      - run: pip install pint open_atmos_jupyter_utils scipy nbconvert ipykernel
      - run: python -m nbconvert --to pdf --execute pint_and_boiling_point.ipynb checkout
      - uses: actions/upload-artifact@v4
        with:
          path: sprawko.pdf

