name: sprawozdanie_pdf
on: push

jobs:
  sprawozdanie_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fix mirrors and install deps
        run: |
          sudo apt-get update || true
          sudo apt-get install -y texlive-xetex inkscape pandoc

      - run: pip install pint open_atmos_jupyter_utils scipy nbconvert ipykernel pympdata

      - run: python -m nbconvert --to pdf --execute pint_and_boiling_point.ipynb --output sprawko.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: sprawko
          path: sprawko.pdf
